language: elixir
sudo: false

elixir:
  - 1.3
  - 1.4
  - 1.5
  - 1.6

before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 --auth &> /dev/null &
env:
  matrix:
    - MONGODB=2.4.14
    - MONGODB=2.6.12
    - MONGODB=3.0.15
    - MONGODB=3.2.13
    - MONGODB=3.4.4
    - MONGODB=3.6.2
